server: 
  port: 8099

api:
  json-place-holder:
    domain: "localhost:8089"
    endpoints:
      stock: /five
      hour: /hourMA
      history: /history

spring:
  application:
    name: bc-stock-web
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html